version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: credit_system
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
